// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.NET.Infrastructure;

#nullable disable

namespace Task.NET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250426210900_ToDoEntity")]
    partial class ToDoEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task.NET.Domain.Entities.ToDo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("iId");

                    b.Property<int>("Complete")
                        .HasColumnType("int")
                        .HasColumnName("iComplete");

                    b.Property<DateTime>("DateTimeOfExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtDateTimeOfExpiry");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sDescription");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sTitle");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.ToTable("ToDos");
                });
#pragma warning restore 612, 618
        }
    }
}
